# userbot-v0\core\db_whitelists.py
from typing import Dict, List

# Ma'lumotlar bazasiga kirishga ruxsat etilgan jadvallar ro'yxati
DB_TABLE_WHITELIST: List[str] = [
    "accounts",
    "admins",
    "dynamic_settings",
    "scheduled_jobs",
    "task_logs",
    "applied_migrations",
    "initial_data_loaded",
    "afk_settings",
    "afk_mentions",
    "afk_ignored_users",
    "notes",
    "telegraph_accounts",
    "translate_settings",
    "translate_history",
    "tts_settings",
    "tts_auto_chats",
    "account_settings",
    "logged_media",
    "ai_knowledge_base",
    "ai_auto_reply_settings",
    "ai_personalities",
    "ai_commenter_channels",
    "ai_usage_stats",
    "profile_snapshots",
    "account_2fa_settings",
    "text_log_settings",
    "text_log_ignored_users",
    "group_settings",
    "captcha_challenges",
    "digest_settings",
    "animator_random_items",
    "task_queue",
]

# Ma'lumotlar bazasiga kirishga ruxsat etilgan ustunlar ro'yxati (jadval bo'yicha)
DB_COLUMN_WHITELIST: Dict[str, List[str]] = {
    "accounts": ["id", "session_name", "api_id", "api_hash", "telegram_id", "is_active", "status", "created_at", "last_login"],
    "admins": ["user_id", "permission_level", "added_by", "added_date"],
    "dynamic_settings": ["key", "value", "type", "description", "last_modified"],
    "scheduled_jobs": ["job_id", "account_id", "task_key", "trigger_type", "trigger_args", "job_kwargs", "status", "created_at", "last_run"],
    "task_logs": ["id", "task_key", "run_at", "duration_ms", "status", "details"],
    "applied_migrations": ["id", "filename", "applied_at"],
    "initial_data_loaded": ["id", "script_name", "loaded_at"],
    "afk_settings": ["account_id", "is_afk", "reason", "afk_since", "groups_enabled"],
    "afk_mentions": ["id", "afk_account_id", "chatter_id", "chat_id", "message_id", "message_text", "mention_time"],
    "afk_ignored_users": ["owner_account_id", "ignored_user_id"],
    "notes": ["id", "account_id", "name", "content", "note_type", "source_chat_id", "source_message_id", "created_at", "updated_at"],
    "telegraph_accounts": ["id", "userbot_account_id", "short_name", "author_name", "access_token", "is_active", "created_at"],
    "translate_settings": ["account_id", "default_target_lang"],
    "translate_history": ["id", "account_id", "provider", "source_lang", "target_lang", "source_text", "translated_text", "timestamp"],
    "tts_settings": ["userbot_account_id", "key", "value"],
    "tts_auto_chats": ["userbot_account_id", "chat_id"],
    "account_settings": ["account_id", "media_log_channel_id", "log_all_private_messages", "created_at", "updated_at"],
    "logged_media": ["id", "account_id", "chat_id", "message_id", "media_type", "file_id", "file_size", "caption", "timestamp"],
    "ai_knowledge_base": ["id", "account_id", "trigger_phrase", "response_text", "created_at"],
    "ai_auto_reply_settings": ["account_id", "is_enabled"],
    "ai_personalities": ["id", "userbot_account_id", "name", "prompt", "cooldown_seconds", "created_at", "updated_at"],
    "ai_commenter_channels": ["id", "userbot_account_id", "channel_id", "personality_name", "is_active", "delay_min_seconds", "delay_max_seconds", "include_keywords", "exclude_keywords", "last_comment_at"],
    "ai_usage_stats": ["id", "userbot_account_id", "stat_date", "call_count"],
    "profile_snapshots": ["id", "account_id", "snapshot_name", "first_name", "last_name", "bio", "photo_blob", "created_at"],
    "account_2fa_settings": ["account_id", "password_hash", "hint", "email", "created_at", "updated_at"],
    "text_log_settings": ["id", "account_id", "chat_id", "is_enabled", "log_edits", "log_deletes", "log_joins", "created_at", "updated_at"],
    "text_log_ignored_users": ["account_id", "user_id"],
    "group_settings": ["id", "userbot_account_id", "chat_id", "welcome_enabled", "welcome_message", "welcome_timeout", "goodbye_enabled", "goodbye_message", "captcha_enabled", "captcha_timeout", "captcha_penalty", "clean_service_messages", "created_at", "updated_at"],
    "captcha_challenges": ["id", "chat_id", "user_id", "correct_answer", "captcha_message_id", "created_at"],
    "digest_settings": ["account_id", "delivery_time", "is_enabled", "confirmation_message_id", "chat_id", "created_at", "updated_at"],
    "animator_random_items": ["id", "account_id", "item_type", "item_value", "created_at"],
    "task_queue": ["id", "account_id", "task_name", "payload", "status", "created_at", "processed_at"], # misol uchun, agar task queue bo'lsa
}